language: php

# Only test the master branch and SemVer tags.
branches:
  only:
    - master
    - /^v*[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install

script:
  - composer test-all

after_success:
  - travis_retry php vendor/bin/coveralls
